services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    tty: true
    volumes:
      - ./data/ollama:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./data/open-webui:/app/backend/data

volumes:
  ollama:
  open-webui:
